draw_set_halign(1)
draw_set_valign(1)
draw_set_alpha(dalpha)
draw_set_color($808080)
draw_text_transformed(screen_width * 0.5, screen_height * 0.5 - 12, "ENTER PROFILE NAME", 2, 2, 0)
draw_set_color($ffffff)
draw_text_transformed(screen_width * 0.5, screen_height * 0.5, kstring, 2, 2, 0)
draw_set_alpha(1)
